{{- if and .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "velero-agent.fullname" . }}
  labels:
    {{- include "velero-agent.labels" . | nindent 4 }}
rules:
  - verbs:
      - get
    nonResourceURLs:
      - '/readyz'
      - '/healthz'
      - '/livez'
      - '/version'
  - apiGroups: [ "" ]
    resources:
      - namespaces
    verbs:
      - get
      - list
  - apiGroups: ["velero.io"]
    resources: ["*"]
    verbs:
      - "*"
{{- end }}
