apiVersion: v2
name: velero-agent
description: A Helm chart for Velero UI
type: application

version: 0.14.0

appVersion: "0.10.0"

kubeVersion: "^1.16.0-0"

annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/changes: |
    - kind: changed
      description: upgrade app version to 0.10.0
keywords:
  - backup
  - velero
  - dashboard
sources:
  - https://github.com/mksantanu/velero-agent
  - https://github.com/vmware-tanzu/velero
maintainers:
  - name: Santanu
    email: mksantanu@me.com
