apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero-agent
  namespace: velero-agent
spec:
  selector:
    matchLabels:
      name: velero-agent
  template:
    metadata:
      labels:
        name: velero-agent
    spec:
      serviceAccountName: velero-agent
      containers:
      - name: velero-agent
        image: velero-agent:latest
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: http
        readinessProbe:
          httpGet:
            path: /health
            port: http
        env:
          - name: BASIC_AUTH_PASSWORD
            value: admin
          - name: VELERO_UI_NAMESPACE
            value: velero-agent
          - name: POLICY_FILE_PATH
            value: /policies/policies.csv
        volumeMounts:
          - name: policies
            mountPath: "/policies"
            readOnly: true
      volumes:
        - name: policies
          configMap:
            name: velero-agent
            items:
              - key: policies.csv
                path: policies.csv
