apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: velero-agent-role
  namespace: velero-agent
rules:
  - apiGroups: [""]
    resources:
      - pods/log
      - pods/status
      - pods
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: velero-agent-role
  namespace: velero
rules:
  - apiGroups: [""]
    resources:
      - pods/log
      - pods/status
      - pods
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["velero.io"]
    resources: ["*"]
    verbs:
      - "*"

