apiVersion: v1
kind: Service
metadata:
  name: velero-agent
  namespace: velero-agent
spec:
  type: ClusterIP
  selector:
    name: velero-agent
  ports:
  - port: 80
    name: http
    targetPort: http
    protocol: TCP
